#!/bin/sh

# Opens .sent files as sent presentations.
file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

textype() {
	command="pdflatex"
	( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
	$command --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
	}

# upto () {
#     if [ -z "$1" ]; then
#         return
#     fi
#     local upto=$1
#     cd "${PWD/\/$upto\/*//$upto}"
# }

case "$file" in
	*config.h) sudo make install ;;
	*.md) pandoc "$file" --pdf-engine=xelatex -o "$base".pdf ;;
	*.tex) textype "$file" ;;
	*.py) python "$file" ;;


# espresso
# zenburn
# kate
# monochrome
# breezedark
# haddock
#

	# *\.ms) refer -PS -e "$file" | groff -me -ms -kejpt -T pdf > "$base".pdf ;;
    #     *\.c) cc "$file" -o "$base" && "$base" ;;
	# *\.go) go run "$file" ;;
	# *\.sent) setsid sent "$file" 2>/dev/null & ;;
	# *) sed 1q "$file" | grep "^#!/" | sed "s/^#!//" | xargs -r -I % "$file" ;;
	# *\.mom) refer -PS -e "$file" | groff -mom -kejpt -T pdf > "$base".pdf ;;
	# *\.rmd) echo "require(rmarkdown); render('$file')" | R -q --vanilla ;;
esac
