#!/bin/sh

# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.
# If no url given. Opens browser. For using script as $BROWSER.

browser=${BROWSER:-firefox}
[ -z "$1" ] && { "$browser"; exit; }


case "$1" in
    *mkv|*webm|*mp4|*youtube.com*|*youtu.be*|*hooktube.com*|*bitchute.com*)
        setsid mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" ;;
    *png|*jpg|*jpe|*jpeg|*gif)
        curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")"  ;;
    *mp3|*flac|*opus|*mp3?source*)
        setsid tsp curl -LO "$1" ;;
    *)
        "$browser" "$1" ;;
esac
