#!/bin/sh

# Increase key speed via a rate change
xset r rate 275 60
# Map the caps lock key to super...
# setxkbmap -layout us -variant altgr-intl -option caps:super
# If you don't want a us international keyboard, rather whatever keyboard
# you set in your installation, comment out the above line and uncomment
# the one below.
# setxkbmap -option caps:super  # ENABLE

# But when it is pressed only once, treat it as escape.
# killall xcape ; xcape -e 'Super_L=Escape' # ENABLE

# Map the menu button to right super as well.
# xmodmap -e 'keycode 135 = Super_R'
# keycode 135 = Super_R NoSymbol Super_R


setxkbmap -option caps:escape
# xmodmap -e "keycode 9 = Caps_Lock NoSymbol Caps_Lock"
