#!/bin/sh

# Display contents of selection via dunst if running.
! pgrep -x dunst >/dev/null && echo "dunst not running." && exit

clip=$(xclip -o -selection clipboard)

prim=$(xclip -o -selection primary)

[ "$prim" != "" ] && notify-send "Clipboard:
$clip"
[ "$clip" != "" ] && notify-send "Primary:
$prim"
