#!/bin/bash
# Toggle touchpad. Requires xf86-input-synaptics.
(synclient | grep TouchpadOff.*1 && synclient TouchpadOff=0)>/dev/null && echo "TouchPad reactivated." && notify-send "TouchPad reactivated." && exit
synclient TouchpadOff=1 && echo "TouchPad deactivated." && notify-send "TouchPad deactivated."
