#! /usr/bin/bash
# Sets right perspective when monitor is plugged in
# Needed by udev rule /etc/udev/rules.d/95-hotplug-monitor
export DISPLAY=:0
export XAUTHORITY=/home/kgnugur/.Xauthority

function connect(){
  xrandr --output HDMI-2 --primary --auto  --left-of eDP-1
}

function disconnect(){
  xrandr --output HDMI-2 --off 
}

xrandr | grep "HDMI-2 connected" &> /dev/null && connect || disconnect
