#! /usr/bin/bash
# Sets right perspective when monitor is plugged in
# Needed by udev rule /etc/udev/rules.d/95-hotplug-monitor
export DISPLAY=:0
export XAUTHORITY=/home/kgnugur/.Xauthority

function connect(){
  xrandr --output HDMI2 --primary --auto  --left-of eDP1
  xrandr --auto
}

function disconnect(){
  xrandr --output HDMI2 --off
}

xrandr | grep "HDMI2 connected" &> /dev/null && connect || disconnect
