#! /usr/bin/bash
# Sets right perspective when monitor is plugged in
# Needed by udev rule /etc/udev/rules.d/95-hotplug-monitor
export DISPLAY=:0
export XAUTHORITY=/home/kgnugur/.Xauthority

function connect(){
  xrandr --output HDMI-2 --primary --auto  --left-of eDP-1
  xrandr --auto
  # Fix feh background if screen size/arangement has changed.
  feh --bg-scale "$HOME/.config/wall.jpg"
  # Restart dunst to ensure proper location on screen
  pgrep -x dunst >/dev/null && killall dunst && setsid dunst &
  # Re-remap keys if keyboard added (for laptop bases)(I dont know if this is
  # needed)
  remaps
}

function disconnect(){
  xrandr --output HDMI-2 --off
  # Fix feh background if screen size/arangement has changed.
  feh --bg-scale "$HOME/.config/wall.jpg"
  # Restart dunst to ensure proper location on screen
  pgrep -x dunst >/dev/null && killall dunst && setsid dunst &
  # Re-remap keys if keyboard added (for laptop bases)(I dont know if this is
  # needed)
  remaps
}

xrandr | grep "HDMI-2 connected" &> /dev/null && connect || disconnect
