#!/usr/bin/env bash

: "${CM_LAUNCHER=dmenu}"
: "${CM_DIR="${XDG_RUNTIME_DIR-"${TMPDIR-/tmp}"}"}"
: "${CM_HISTLENGTH=8}"

major_version=5

shopt -s nullglob

cache_dir=$CM_DIR/clipmenu.$major_version.$USER
cache_file_prefix=$cache_dir/line_cache

if [[ $1 == --help ]] || [[ $1 == -h ]]; then
    cat << 'EOF'
clipmenu is a simple clipboard manager using dmenu and xsel. Launch this
when you want to select a clip.

All arguments are passed through to dmenu itself.

Environment variables:

- $CM_DIR: specify the base directory to store the cache dir in (default: $XDG_RUNTIME_DIR, $TMPDIR, or /tmp)
- $CM_HISTLENGTH: specify the number of lines to show in dmenu/rofi (default: 8)
- $CM_LAUNCHER: specify a dmenu-compatible launcher (default: dmenu)
EOF
    exit 0
fi

if [[ "$CM_LAUNCHER" == rofi ]]; then
    # rofi supports dmenu-like arguments through the -dmenu flag
    set -- -dmenu "$@"
fi

list_clips() {
    cat "$cache_file_prefix"_* /dev/null | LC_ALL=C sort -rnk 1 | cut -d' ' -f2- | awk '!seen[$0]++'
}

if [[ "$CM_LAUNCHER" == rofi-script ]]; then
    if ! (( $# )); then
        list_clips
        exit
    else
        # https://github.com/koalaman/shellcheck/issues/1141
        # shellcheck disable=SC2124
        chosen_line="${@: -1}"
    fi
else
    chosen_line=$(
        list_clips | "$CM_LAUNCHER" -l "${CM_HISTLENGTH}" "$@"
    )
fi

[[ $chosen_line ]] || exit 1


# If chosen line is not link search it with a search engine
# If chosen line is a link open it with browser
browser=${BROWSER:-firefox}
search_engine=${SEARCHENGINE:-duckduckgo}

# Detect if url
if [[ "$chosen_line" =~ ^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$ ]]; then
    $browser "$chosen_line"
else
    if [[ $search_engine == "duckduckgo" ]]; then
        $browser "https://duckduckgo.com/?q=$chosen_line&t=ffab&atb=v1-1"
    elif [[ $search_engine == "google" ]]; then
        $browser "http://www.google.com/search?q=$chosen_line"
    fi
fi


file=$cache_dir/$(cksum <<< "$chosen_line")

if ! [[ -f "$file" ]]; then
    # We didn't find this in cache
    printf 'FATAL: %s not in cache (%s missing)\n' "$chosen_line" "$file" >&2
    printf 'Please report the following debug information:\n\n' >&2
    wc -l "$cache_file_prefix"_* >&2
    grep -nFR "$chosen_line" "$cache_dir" >&2
    stat "$file" >&2
    exit 2
fi

for selection in clipboard primary; do
    xsel --logfile /dev/null -i --"$selection" < "$file"
done
