#!/bin/bash

choice=$(echo -e "Suspend\nPowerOff\nRestart" | dmenu -fn "monospace:size=16" -i -p  "Choose a option")

if [ $choice = "Suspend" ]; then
    systemctl suspend
elif [ $choice = "PowerOff" ]; then
    shutdown -h now
elif [ $choice = "Restart" ]; then
    reboot
fi
